# Generated by Django 5.0.7 on 2024-07-09 19:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermercado', '0002_alter_produtos_cod_barras'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='criado',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 7, 9, 19, 10, 1, 821213, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produtos',
            name='valid',
            field=models.DateField(verbose_name='Validade'),
        ),
    ]
